### ISSUE TITLE
`E2E`: Investigate and fix issues in `TokenCreateTransaction` tests

### ISSUE THREAD

**Issue by ivaylogarnev-limechain** [hiero-ledger/hiero-sdk-tck#244]
### Description

Found some issues in the `origin/00231-tck-implement-json-rpc-method-for-tokencreatetransaction`:

`Test (#1) Creates a token with an auto renew account` **(specifically the 2nd expect call)** is failing for two reasons. First, the `MirrorNodeClient` class is not correctly retrieving data in the `getTokenData()` method. Second, the data from both the `Consensus` and `Mirror` **clients** must be **awaited**.

Upon reviewing the `MirrorNodeClient` class, I noticed the API endpoints didn’t align with the Swagger documentation and `verifyTokenCreationWithInitialSupply` helper function within the `tokenCreateTransaction` file must be awaited.
### Steps to reproduce

1. Clone and run an C++ SDK server in branch `00757-tck-c++-implement-json-rpc-methods-for-tokencreatetransaction`
2. Clone the TCK
3. Checkout branch `origin/00231-tck-implement-json-rpc-method-for-tokencreatetransaction`
4. Run `npm test test/token-service/test_tokenCreateTransaction.js`

### Hedera network

`hedera-local-node` and  `testnet`

### Version

latest

### Operating system

MacOS

**Comment by rwalworth** [comment]
This work involved with this issue is now a part of #252.

**Comment by rwalworth** [comment]
@ivaylogarnev-limechain you fine closing this since #252 has been merged?

**Comment by ivaylogarnev-limechain** [comment]
> @ivaylogarnev-limechain you fine closing this since #252 has been merged?

Yep, let we close it :)

**Comment by ivaylogarnev-limechain** [comment]
This was completed in pull request #252.
