### ISSUE TITLE
Investigate use of helper functions and templates for use between tests

### ISSUE THREAD

**Issue by rwalworth** [hiero-ledger/hiero-sdk-tck#260]
With several test suites implemented and merged, a lot of code has been copy-pasted as several test follow the same philosophies and a lot of parameter types run the same kinds of tests. We should look into how we can better organize and modularize these tests to improve development time down the road.

**Comment by rwalworth** [comment]
@ivaylogarnev-limechain you think this can be closed or are there still investigations/changes you wanna make here?

**Comment by ivaylogarnev-limechain** [comment]
> @ivaylogarnev-limechain you think this can be closed or are there still investigations/changes you wanna make here?

we can close this
